import:
- vault.yml
branches:
  only:
  - main
  - integration-regresion-tests
  - vault-tests
dist: bionic
language: ruby
vault:
  api_url: https://vault-dwztla.travis-ci.com
  token:
    secure: "oXr3NviX2fhOyMiG0hNfIGU27+/c1O55UsONFLidvnCQImbLi3yO5Mw7Nu/zOIt2c63oatc1Z2oEgG3Xm7Oa5uX2QEXBdkCsVEQ14g+2szjUR+I4Pms0QMiUWSbsQy8uQsaZXw4+riElkk/n/kDZRmBxZhrvRhy3gJeFOelRHRRannkbP3JDDfkgizFqylSzlhJwNuQcuoS0XCa7OqsAi56E7EvKElUQ458MOm6CtjELp3QsYhkS6aB4eoSnVpJEbc2ia2nNThORFQKm0fsZXouvS3s0H0WC7C27NhdSTGQho6n/HgfePbKhF3KOFKzb6w844SJ6RHMxWMwsdZrVvByWQPUBtAvQHrUOh93chWG0YuA/TCdF7JpDXldnlAOqjBPHrxmEsMXHkJDA/2bmF4q3ky8dJBorfInI/9Fpm5EH7hyAFqoBmSkKCPZRj7OIm6WeB5euTKMmsSWpGzIXj0OlIF5XDoCE+5L2fGL155uYpT/2p7SFVTObo1oN2GL8RK1SjtldzAyn1EQrPDb0CNeYN9qOrgKxaz+rEglvOoY7NP8e84kXsQsZfpzr/1M5IW0c6t0YtTjRtlqo24VK+oyKRdXEZ38cdlu8w/kzWHFv8P/wFFJgCbfGxROpjh4J3OcUUaAaZkuqD9Y7WdyoU2Ofu3d8byUPxRkElWHD6BI="
  secrets:
    - namespace:
        - name: ns1
        - project_id/secret_key_a
        - project_id/not_existent
    - ns2/project_id/secret_key_b
    - ns2/project_id/not_existent_key
script: ruby ./source/vault_check.rb
env:
  global:
  - secure: J6PkiwYONd/W1PB5FOtJ46i6Ta7MGx05znAVGcW5E5jDDPBMuOL8Ecq/0vlbPsFGPlwHZtnn4FjWtg7X183gWtRZ0eGdY6GE/5hzL1g65aw0XyLXBSRzu5R2IQYlbNDxclXjBhVV7NvH4z63EFSKkbaxVuuUQXDbNXjgEJDMXfAQqSxlz/+0Qh/yJNvsJRnG3soT3c0fHa839k32yqjIGJqO5VJDEp8O5sRaEIbTqF4v6PwkKDY58MAfrNFMWuMxfzUAAQj2bt1S5E9baajv2rllJgS/i9gNFO5XKoVGQN3UbFI1rpR+oGc4nWn6gdHpoLA1j5aMyLVHw3dgKrv5OyysOP+kF0T8sgY0P3WThNJxwK8NKMymUcjCx9mmu+ZHxA9qZHGPBf6lbzVpF9XeOn7BXpwD10dFOlPEYgKqAuiecNVnXHFtr42LJryYZJpL/DjP8BdMaaH24jaNZDpUQw147cpcpZXvHv+LQjUpRQSxQx+iLO2SoEzdg7fHYoIAbGO9tZB1j/uS+4JYTQv7WJKam84iUkM74FF2l3JHU0zjdT5sb0qU91aUAHDUuvV4t997ngE/rMw22scKbVGQtVsDiMYEBbfqX3wnFwCSnlYfn9dJEU/pPjlS/qaxcehvGxII5TJMZtjBFYIgApo5koAn0S6G1jH1CcvMRDH5m9A=
