import:
- stages.yml
- ifs.yml
- ifs-with-envs.yml
- secure.yml
- sleep.yml
branches:
  only:
  - main
  - integration-regresion-tests
os: linux
dist: bionic
language: ruby
rvm:
- 2.7.5
jobs:
  allow_failures:
  - os: linux
    dist: bionic
    language: ruby
    rvm: 2.7.5
env:
  global:
  - secure: oql/vsm12btavaWCpB1TJFOESRm+R7P2wvWKKMGmIKOtUUw+2GcGQnCSI63YwEGzGIoYAoqL5OjK/mHNAm1Zft4Oeg0JYke1apJMZpZPyjEE5L3RW07jHf3DopCy+pPZi+XUqTEDWGHfk+jkEkIlPeksTWY55H9UUNUcy5jtpLJJpWpf4xWJQiQVBh4EqvNeUl3/TVk0lOtCXXMvQGlwABD26ZljlP3XeXSDQ9CwBatPY4wUGLz6NS8Zo6AKtZ5IOpTOly/fNfDhKKeaI3wKtnL60neiF6Q+gZdZrTTOEZsvJ6vtVEqqq3ZhE6bPsxNm4RRHxmlUNlnkVB1yAAoqpIT1lmie63a/t/ymYNSt1Enyct3MN3pWQkRbab6UpzH1zi2L7utbmYlEmNknc/OrLzS+eWwQuv9E5fYOcva8WvBSuRBlcnN5pjN7XlqBTTUVw7BA3B/axf9Pl+ebSF2ktRSdM5bOF6tXHlEaoPQQ+M591q1iT4tg83hTtP9Kcu07fgou7b2pICb8evxB9iYbtClb2xzlssn5L8pEZn5aAmE35DZD1+xl0t0zFXZEtF1/MtJsQpvc5O5peWKunDNrW+7X0TCCoQ4StemyLNYJ7XyHUlPCimKkfMUAdrWF1FpHtgQ0dsaP2xf5tjE6lK0Zww+tF0DHhvPuWsGYuBebMMo=
