import:
- stages.yml
- ifs.yml
- ifs-with-envs.yml
#- secure.yml

branches:
  only:
  - main
  - integration-regresion-tests
os: linux
dist: bionic
language: ruby
rvm:
- 2.7.5
jobs:
  allow_failures:
  - os: linux
    dist: bionic
    language: ruby
    rvm: 2.7.5
#env:
#  global:
#    secure: "GcF/+D82cnKExiK/xMPH3NbAa73ZiqGb5727TODqwCroEAJUy0O7aJe/r6TYnUQwnyvySANlEWQzGXFY0d/X5AZaESZcXjxWYVcSR+Vn/oz6LLfISWrUUpB5cgKBby+sjn/wPInQftsCLh4Wu4h8TqZBPQ6AlTd3eOCrXOzUuVvyCJmxU/Lu79D34qpgNvmrsrKn7eEXqKy96LixDTshjd/w5vUnfb3ZWoZynm4Qon4RbkGr4l6L8mA2YpXNHRcB2QJdlvLEj3G19TW9AnVjKUMbADh7/pYlWL4/nkzbMu6PNNsIlU3mnEg0nx21RHGNnFejPJuqQ1l8woYI7puoAr8i3hCMTjdbGmsvyO5cLY++hs/TohHBrg5PqNryMF2GoMJmiSBwJriNa2VdJB02VZY/NHf5f79mydzDR20lTGKZrs7R+3TQDY6iffZn8qy68e0heMMxQ0BRtH2nDdg8LRIsAR+SReWwcTriN0dPLvf+5pD8ZiBVg5NpgNZVlrFzcGCuqLZ0pg6HPgxtiKRFkzCv3aSYFJz5ZVZfXKS9UG231rZSz3fKizIIZEov4zIiKHIFwBatYxc0p1OfryaBZ/wX6X6nF+QMsS6WqQH3FuVnIrpDGjM3rJ8MQz9+2TfZqH5zAFKZZ1kBahysYnT7FbUPiH0Y5FXFnpK0mSfNLcQ="
