import:
- stages.yml
- ifs.yml
- ifs-with-envs.yml
- secure.yml

branches:
  only:
  - main
  - integration-regresion-tests
os: linux
dist: bionic
language: ruby
rvm:
- 2.7.5
jobs:
  allow_failures:
  - os: linux
    dist: bionic
    language: ruby
    rvm: 2.7.5
env:
  global:
    secure: 5TAFE8T4muz6N8z6BdAYfusmxmS/cCU138VjZgccLMendQrhd2YGn2j0nlVEJLHMgOJ73ARju+fXeeQG+8ZesYXcFKaZeESDDgQnXwuv1wVcn4BQDw1O8y72exN0W3nY92xp4hWXfzN7E2jk2eMU6YC5cmoOBKWsFU2joBrrMORcGnDNhM8Wg0BTO7lbDVYZHZF/b8PYlNtiu7Dx3KyDSq528pmSaAHrWkhgXJ6YxXMgFywi9nTfUQa/IhfCBVUvGk3KIyGgsqGug76cbYh/+eDfp7GbrUd+RCzkbP6KUZ/ge0MdAbDl+1ZL+Y1uPuhUnCusf1btPDnazVv03LC3HUBdQ1sQvCj09/5f59BZh2jL/hbo+gQYsCRiOJq7kfgst0GI1VwchY8vsAjGJcIm8rMwksJ94EBXWS91inCDGxvAgZtGA6uyl0v2EEPKP+Qp6ycI8aolyDgM7NtsKof5NdBBJbMHfwJOUbWsSo3ciR/41ucHlR8ldvMGiuaBRbTVxhM4SqkeJkbmLQt1C9MyyVykDR1gpS25eJe8vqGzJjHuE2cTFvx29Pf2pPeo8thIiVKHV8H/qhNI7vqQuQCfnsCeYw87hj5TCrmFdN8V8wgy6txiCOTkwShFCBbBMay9hjV6hs+O+xJiCZIB1izEJhhrEIHiL3sljh7ssrz53M=
