# cases for build-stages https://docs.travis-ci.com/user/build-stages/
# - sequence of stages
# - named stages
# TODO: add bash output whther expected result of the job is to pass or fail at each job in matrix
jobs:
  include:
    - stage: "First"
      name: "First stage"
      script: ruby ./source/ruby_hello.rb
    - stage: "Second"
      name: "Second stage"
      script: ruby ./source/fail.rb
    - stage: "Next"
      name: "Next stage"
      script: ruby ./source/fine.rb
