vault:
  api_url: https://vault-dwztla.travis-ci.com
  token:
    secure: "ZOkd5QXvkfhrI2mNxLWTw1by8t9EbdHrWHIsB8je1SvDWmrkop5I1orppFPgy6ik/zARI/ycKGhLe+cgcc3BlDQzgzOy7p6u3C+dNUrY+7jZiTDoQjm6QcI5nc1D7OqlsXpTlWcXRvkUQJOKRWGHO7Gx+I+XQ++Wj9WJcCWsyrY76rRSiXZk7AKPHzgFTIyXO6bjIhp0Ah0+UpoNGSyzlVavJ7vk3mwnROynfqsWzQGiMUKiYzJJeSyomuHncj2hS1jd67BQR3FuLhn1kBfGnslQPreDcoHKvF4xRxHT1vQpH2fwMmsxTKVYOKmxWyXexrR6Q9C2MMdPp94VHgBLRxywVsmG/n2nLcstggMRLzWt0MT71X0vE1wcxaKshEp7/QWxIW+7bFi0PeKZBSJaTm4j9V/W/Yksb401AdNqAZSAmf1Zh3ELZ6D1Du3qGAHX01ZvrSmBCrz2ZoeUlrSGnHbfDt9NWqUvRLhaUBHc3MWQkXM8WlM4LhGRKAXRPZbR97y6DTtYYEPn0asMjecYuUVfEjGH863Ys3cWNUNtVhSvPjKCRACCiZ1AZTDxvC29NqGx+1+f5OEF3WPCFscJnLbwSwqy+GKFz9HzqU50Pzki5ZjUmufNEk0Q+nT4EIYErksIIBOGbDg2RXvQIWTUzO4yvEku2YaIJWqBAMZ5aYE="
  secrets:
    - :namespace:
      - :name: ns1
      - project_id/secret_key_a
      - project_id/not_existent
    - :namespace:
      - :name: ns2
      - project_id2/secret_key_c
      - project_id2/secret_key2_d
    - ns1/project_id/secret_key_e
    - ns1/project_id/it_does_not_exist
    - ns2/project_id/secret_key_g
    - ns2/project_id/secret_key2_h
env:
  - MY_NOT_IMPORTANT_VARIABLE=meh
  global:
    - GLOBAL_NOT_IMPORTANT=global
dist: bionic
language: ruby
jobs:
  include:
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/list_envs.rb
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token:
          secure: "ZOkd5QXvkfhrI2mNxLWTw1by8t9EbdHrWHIsB8je1SvDWmrkop5I1orppFPgy6ik/zARI/ycKGhLe+cgcc3BlDQzgzOy7p6u3C+dNUrY+7jZiTDoQjm6QcI5nc1D7OqlsXpTlWcXRvkUQJOKRWGHO7Gx+I+XQ++Wj9WJcCWsyrY76rRSiXZk7AKPHzgFTIyXO6bjIhp0Ah0+UpoNGSyzlVavJ7vk3mwnROynfqsWzQGiMUKiYzJJeSyomuHncj2hS1jd67BQR3FuLhn1kBfGnslQPreDcoHKvF4xRxHT1vQpH2fwMmsxTKVYOKmxWyXexrR6Q9C2MMdPp94VHgBLRxywVsmG/n2nLcstggMRLzWt0MT71X0vE1wcxaKshEp7/QWxIW+7bFi0PeKZBSJaTm4j9V/W/Yksb401AdNqAZSAmf1Zh3ELZ6D1Du3qGAHX01ZvrSmBCrz2ZoeUlrSGnHbfDt9NWqUvRLhaUBHc3MWQkXM8WlM4LhGRKAXRPZbR97y6DTtYYEPn0asMjecYuUVfEjGH863Ys3cWNUNtVhSvPjKCRACCiZ1AZTDxvC29NqGx+1+f5OEF3WPCFscJnLbwSwqy+GKFz9HzqU50Pzki5ZjUmufNEk0Q+nT4EIYErksIIBOGbDg2RXvQIWTUzO4yvEku2YaIJWqBAMZ5aYE="
        secrets:
           - :namespace:
             - :name: ns1
             - project_id/secret_key_a
             - project_id/not_existent
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/list_envs.rb
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/ruby_hello.rb
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: "people put sometimes secret tokens in open text format"
        secrets:
          - mana/mana/aaa
          - mana/mana/bbb

