vault:
  api_url: https://vault-dwztla.travis-ci.com
  token:
    secure: "I1ReDgLhqYAqIF9Fe49H2euF3qX4hG4axLo6yArViPBh20i+aR6UOFdOIrUVbiZMwH6B4LrSfOoZ1JNFAmLE8sM/h/Pn193nL2msTNELRXs5bGDqEQchYcJJhR3dEg4xqG2sDfpjVZLcr78wdzniw109C7HwpZbabkUddXrjxVZoqh9Uburd/PrfoYGNeWpLyva9dgpq1X5qM8GJgfkKVHEJGcL7tK5ROnVCFmQ5AkiRMMGWRaHLTp1sz7Avd8mcTopy9OJHFWzk/o47Yq1nZDil/w1p4uFQbCVHtwkQnUsfu3b+2Zk0qjhzBRd8h6HMdIn7kg0wHKScFp18vrMaRMIg5vZyrfSeCKhrlc3Hj/Y7iriak3gjJSrHNNaWjr0s0zaBa2zrFy7DtsDPm+Sr9/pYG9QmTVfVveieBuccxKP77+F9VRz76nFuD67phK1/wOXLGQFM44Lp92aC9Ntebshz3Ojj+gjJpr67Vy+w6QJ2bBCzQ9crXxFPbXEUYqs0Z3Nbykb+HJNnrbntbZaMEzI2UEAdMO5Ys3FgC0bI2Nk6ygbIvxhOtSf2+vAMdlkPOpedr4w7OrHpOPt/+SBcLR4983HtELSEdM7un0raoOzUR94xaWMcji5pMqpePLxfv+U9aoXG7rY0Csf2953oVgd5RuIHwjkU8iYVNHwUol8="
  secrets:
    - ns1/some_id/datum
    - ns2/some_id2/aaa
os: linux
dist: bionic
language: ruby
jobs:
  include:
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/ruby_hello.rb
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token:
          secure: "Ms2EkOhi69IMKVmqO26CcM8otLp48LHZi6eK+Xs1ZklntiMV8tu80KxEAEPEz3Z5nq5Z2LVco7m1lhw4xPAFbgkzfTFR6LFj1wkj56zXU63INF1hYtp5opGUP1gilzzCZofogyY8fnysw/K3XzR+7fNdAsUswlWRRry1yjTnbI+oYIaXozoumZq3CS0Z2LG4cVZMTSUxK4d+8HJCvtKEx6K/UpzI9togCqdY9aPTlbUlv7C77kUAjEaUMCubHqrttTi/79u6hT+xB9y8tH8bQDv3t5IHQ5RRbLoogDVxz6aAv5/YGiDAjABMh6JKrsHLiYLNrkfRP5EoCaG8Yi6z202wjlF1NMBK1ZfjMAmQLad/8qqd5p9geEklKMGI2PX2Vq9/nqcVGAfS956HQ9XpUKbTTcH11boFp4lDV8Az43EDYPRz2o4yXaunu/0k/JaFqdoBNbc4FadKytvF1pZh8R+bUsObvhkzQW+h8xMC7Fe8xaTv2iHuhEWn3Iz5tdvwh+irbmaYeNOToMzmGf2lJtJmmkfyN9ks/epsuMCqIWrlkZKPF3YJfvIqPZNqXTG5XwIqEHKcI+Jmm6tcUxcDvgAuZ2FvI+wlJwaXoZ3PBFqhoiDEop4GpgIJODy2s0Z83KeYe51kL6DLxh6GXJNZSEn/pTfwMH4k4p1VIWJvWv8="
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/list_envs.rb

