vault:
  api_url: https://vault-dwztla.travis-ci.com
  token:
    secure: "I1ReDgLhqYAqIF9Fe49H2euF3qX4hG4axLo6yArViPBh20i+aR6UOFdOIrUVbiZMwH6B4LrSfOoZ1JNFAmLE8sM/h/Pn193nL2msTNELRXs5bGDqEQchYcJJhR3dEg4xqG2sDfpjVZLcr78wdzniw109C7HwpZbabkUddXrjxVZoqh9Uburd/PrfoYGNeWpLyva9dgpq1X5qM8GJgfkKVHEJGcL7tK5ROnVCFmQ5AkiRMMGWRaHLTp1sz7Avd8mcTopy9OJHFWzk/o47Yq1nZDil/w1p4uFQbCVHtwkQnUsfu3b+2Zk0qjhzBRd8h6HMdIn7kg0wHKScFp18vrMaRMIg5vZyrfSeCKhrlc3Hj/Y7iriak3gjJSrHNNaWjr0s0zaBa2zrFy7DtsDPm+Sr9/pYG9QmTVfVveieBuccxKP77+F9VRz76nFuD67phK1/wOXLGQFM44Lp92aC9Ntebshz3Ojj+gjJpr67Vy+w6QJ2bBCzQ9crXxFPbXEUYqs0Z3Nbykb+HJNnrbntbZaMEzI2UEAdMO5Ys3FgC0bI2Nk6ygbIvxhOtSf2+vAMdlkPOpedr4w7OrHpOPt/+SBcLR4983HtELSEdM7un0raoOzUR94xaWMcji5pMqpePLxfv+U9aoXG7rY0Csf2953oVgd5RuIHwjkU8iYVNHwUol8="
  secrets:
    - ns1/some_id/datum
    - ns2/some_id2/aaa
os: linux
dist: bionic
language: ruby
jobs:
  include:
    - os: linux
      dist: bionic
      language: ruby
      rvm: 2.7.5
      script:
        - ruby ./source/ruby_hello.rb

